import 'weather_model.dart';
import 'package:flutter/material.dart';

final List<WeatherData> weatherDataList = [
  WeatherData(
    city: '台北',
    temperature: '25°C',
    highLow: '高: 28°C / 低: 22°C',
    description: '晴天',
    icon: Icons.wb_sunny,
    hourlyForecast: [
      HourlyForecast(
        time: '00:00',
        temperature: '22°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(
        time: '02:00',
        temperature: '21°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(
        time: '04:00',
        temperature: '20°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(time: '06:00', temperature: '22°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '08:00', temperature: '23°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '10:00', temperature: '24°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '12:00', temperature: '25°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '14:00', temperature: '26°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '16:00', temperature: '26°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '18:00', temperature: '24°C', icon: Icons.wb_sunny),
      HourlyForecast(
        time: '20:00',
        temperature: '23°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(
        time: '22:00',
        temperature: '22°C',
        icon: Icons.nights_stay,
      ),
    ],

    dailyForecast: [
      DailyForecast(
        date: '2025-03-29',
        highLow: '高: 28°C / 低: 22°C',
        description: '晴天',
        icon: Icons.wb_sunny,
      ),
      DailyForecast(
        date: '2025-03-30',
        highLow: '高: 27°C / 低: 21°C',
        description: '多雲',
        icon: Icons.cloud,
      ),
      DailyForecast(
        date: '2025-03-31',
        highLow: '高: 26°C / 低: 20°C',
        description: '小雨',
        icon: Icons.grain,
      ),
      DailyForecast(
        date: '2025-04-01',
        highLow: '高: 27°C / 低: 21°C',
        description: '晴天',
        icon: Icons.wb_sunny,
      ),
      DailyForecast(
        date: '2025-04-02',
        highLow: '高: 26°C / 低: 20°C',
        description: '多雲',
        icon: Icons.cloud,
      ),
      DailyForecast(
        date: '2025-04-03',
        highLow: '高: 25°C / 低: 19°C',
        description: '小雨',
        icon: Icons.grain,
      ),
      DailyForecast(
        date: '2025-04-04',
        highLow: '高: 24°C / 低: 18°C',
        description: '雷雨',
        icon: Icons.flash_on,
      ),
    ],
  ),
  WeatherData(
    city: '高雄',
    temperature: '30°C',
    highLow: '高: 32°C / 低: 28°C',
    description: '晴天',
    icon: Icons.wb_sunny,
    hourlyForecast: [
      HourlyForecast(
        time: '00:00',
        temperature: '28°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(
        time: '02:00',
        temperature: '27°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(
        time: '04:00',
        temperature: '26°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(time: '06:00', temperature: '28°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '08:00', temperature: '29°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '10:00', temperature: '30°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '12:00', temperature: '31°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '14:00', temperature: '32°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '16:00', temperature: '32°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '18:00', temperature: '30°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '20:00', temperature: '29°C', icon: Icons.wb_sunny),
      HourlyForecast(
        time: '22:00',
        temperature: '28°C',
        icon: Icons.nights_stay,
      ),
    ],
    dailyForecast: [
      DailyForecast(
        date: '2025-03-29',
        highLow: '高: 32°C / 低: 28°C',
        description: '晴天',
        icon: Icons.wb_sunny,
      ),
      DailyForecast(
        date: '2025-03-30',
        highLow: '高: 31°C / 低: 27°C',
        description: '多雲',
        icon: Icons.cloud,
      ),
      DailyForecast(
        date: '2025-03-31',
        highLow: '高: 30°C / 低: 26°C',
        description: '小雨',
        icon: Icons.grain,
      ),
      DailyForecast(
        date: '2025-04-01',
        highLow: '高: 31°C / 低: 27°C',
        description: '晴天',
        icon: Icons.wb_sunny,
      ),
      DailyForecast(
        date: '2025-04-02',
        highLow: '高: 30°C / 低: 26°C',
        description: '多雲',
        icon: Icons.cloud,
      ),
      DailyForecast(
        date: '2025-04-03',
        highLow: '高: 29°C / 低: 25°C',
        description: '小雨',
        icon: Icons.grain,
      ),
      DailyForecast(
        date: '2025-04-04',
        highLow: '高: 28°C / 低: 24°C',
        description: '雷雨',
        icon: Icons.flash_on,
      ),
    ],
  ),
  WeatherData(
    city: '台中',
    temperature: '28°C',
    highLow: '高: 30°C / 低: 26°C',
    description: '多雲',
    icon: Icons.cloud,
    hourlyForecast: [
      HourlyForecast(
        time: '00:00',
        temperature: '26°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(
        time: '02:00',
        temperature: '25°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(
        time: '04:00',
        temperature: '24°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(time: '06:00', temperature: '26°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '08:00', temperature: '27°C', icon: Icons.cloud),
      HourlyForecast(time: '10:00', temperature: '28°C', icon: Icons.cloud),
      HourlyForecast(time: '12:00', temperature: '29°C', icon: Icons.cloud),
      HourlyForecast(time: '14:00', temperature: '30°C', icon: Icons.cloud),
      HourlyForecast(time: '16:00', temperature: '30°C', icon: Icons.cloud),
      HourlyForecast(time: '18:00', temperature: '28°C', icon: Icons.cloud),
      HourlyForecast(time: '20:00', temperature: '27°C', icon: Icons.cloud),
      HourlyForecast(
        time: '22:00',
        temperature: '26°C',
        icon: Icons.nights_stay,
      ),
    ],
    dailyForecast: [
      DailyForecast(
        date: '2025-03-29',
        highLow: '高: 30°C / 低: 26°C',
        description: '多雲',
        icon: Icons.cloud,
      ),
      DailyForecast(
        date: '2025-03-30',
        highLow: '高: 29°C / 低: 25°C',
        description: '晴天',
        icon: Icons.wb_sunny,
      ),
      DailyForecast(
        date: '2025-03-31',
        highLow: '高: 28°C / 低: 24°C',
        description: '小雨',
        icon: Icons.grain,
      ),
      DailyForecast(
        date: '2025-04-01',
        highLow: '高: 29°C / 低: 25°C',
        description: '晴天',
        icon: Icons.wb_sunny,
      ),
      DailyForecast(
        date: '2025-04-02',
        highLow: '高: 28°C / 低: 24°C',
        description: '多雲',
        icon: Icons.cloud,
      ),
      DailyForecast(
        date: '2025-04-03',
        highLow: '高: 27°C / 低: 23°C',
        description: '小雨',
        icon: Icons.grain,
      ),
      DailyForecast(
        date: '2025-04-04',
        highLow: '高: 26°C / 低: 22°C',
        description: '雷雨',
        icon: Icons.flash_on,
      ),
    ],
  ),
  WeatherData(
    city: '台南',
    temperature: '29°C',
    highLow: '高: 31°C / 低: 27°C',
    description: '晴天',
    icon: Icons.wb_sunny,
    hourlyForecast: [
      HourlyForecast(
        time: '00:00',
        temperature: '27°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(
        time: '02:00',
        temperature: '26°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(
        time: '04:00',
        temperature: '25°C',
        icon: Icons.nights_stay,
      ),
      HourlyForecast(time: '06:00', temperature: '27°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '08:00', temperature: '28°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '10:00', temperature: '29°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '12:00', temperature: '30°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '14:00', temperature: '31°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '16:00', temperature: '31°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '18:00', temperature: '29°C', icon: Icons.wb_sunny),
      HourlyForecast(time: '20:00', temperature: '28°C', icon: Icons.wb_sunny),
      HourlyForecast(
        time: '22:00',
        temperature: '27°C',
        icon: Icons.nights_stay,
      ),
    ],
    dailyForecast: [
      DailyForecast(
        date: '2025-03-29',
        highLow: '高: 31°C / 低: 27°C',
        description: '晴天',
        icon: Icons.wb_sunny,
      ),
      DailyForecast(
        date: '2025-03-30',
        highLow: '高: 30°C / 低: 26°C',
        description: '多雲',
        icon: Icons.cloud,
      ),
      DailyForecast(
        date: '2025-03-31',
        highLow: '高: 29°C / 低: 25°C',
        description: '小雨',
        icon: Icons.grain,
      ),
      DailyForecast(
        date: '2025-04-01',
        highLow: '高: 30°C / 低: 26°C',
        description: '晴天',
        icon: Icons.wb_sunny,
      ),
      DailyForecast(
        date: '2025-04-02',
        highLow: '高: 29°C / 低: 25°C',
        description: '多雲',
        icon: Icons.cloud,
      ),
      DailyForecast(
        date: '2025-04-03',
        highLow: '高: 28°C / 低: 24°C',
        description: '小雨',
        icon: Icons.grain,
      ),
      DailyForecast(
        date: '2025-04-04',
        highLow: '高: 27°C / 低: 23°C',
        description: '雷雨',
        icon: Icons.flash_on,
      ),
    ],
  ),
];
